Revert "Update zio from 2.0.0-RC2 to 2.0.0-RC3 (#350)" (#353)
This reverts commit 02e87f0ed8f1ee67a5af20a4d88b044b9dbcab5b.

zio-json is still compiled against RC2, which isn't compatible with RC3:

```
java.lang.NoClassDefFoundError: zio/ZManaged
```

Once zio-json migrates to RC3 we can reapply this update.